### ISSUE TITLE
Missing dependencies & Error with HttpMulti

### ISSUE THREAD

**Issue by dispicio** [hplato/homebridge-httpmulti#10]
Hi,
first of all, thank you very much for your piece of software! I've been successfully managing my shutters and turning on my PC with your module for a while now with my watch =)

Now, as I installed another plugin two days ago and restarted my homebridge-docker instance, HttpMulti stopped working suddently (may be due to a change on my behalf or due to your latest commit, didn't have much time to look in it in detail, ..)

First of all there seem to be missing some dependencies after latest commit.
After installing the following npm modules I don't get any "missing module" errors anymore: 
`request-util, extend, tough-cookie, process-nextick-args, core-util-is, inherits, util-deprecate, aws4, util`

Still, I get this error:
`ERROR LOADING PLUGIN homebridge-httpmulti:
[10/13/2016, 7:54:20 PM] Error: Cannot find module './utils'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.&lt;anonymous&gt; (/usr/lib/node_modules/homebridge-httpmulti/node_modules/request/node_modules/http-signature/lib/parser.js:5:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.&lt;anonymous&gt; (/usr/lib/node_modules/homebridge-httpmulti/node_modules/request/node_modules/http-signature/lib/index.js:3:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)`

`git add -A?` :)

**Comment by hplato** [comment]
I'm in the middle of updating this module to work with IOS10 - the latest commit is a WIP just to back up the work. I have it mostly working, just need to test a few things and update the thermostat piece. You should be able to check out the older version if you use IOS9.

**Comment by dispicio** [comment]
Cool, thanks! Well take your time. Checking out to older version.. :)

But it did already run on iOS 10 without problems  with me (except sometimes when Siri took a long time to send the command and then returned "I didn't hear back", but I guess that's something more network- and/or siri-callback-timeout-related.. But I guess there are problems with some types of things in iOS 10 that won't work?)?

Thank you.

**Comment by hplato** [comment]
Try the latest version, from my tests this morning, I can control objects with both IOS home and siri.

**Comment by hplato** [comment]
I think I got most of the new features working. I can control all items with voice control and the IOS home app

**Comment by dispicio** [comment]
Yap, works pretty nice.
Thanks.
