### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by zwerch** [hplato/homebridge-httpmulti#4]
This project is missing a `LICENSE` file. I strongly advise you to use the [`ISC` license](https://opensource.org/licenses/ISC), because `homebridge` itself and most of the plugins are using it - and also the parts of the code you got from my [`homebridge-blinds` plugin](https://github.com/zwerch/homebridge-blinds) (so you kinda _have_ to use this license 😎).

**Comment by hplato** [comment]
Done. Thanks, I’d really appreciate some help! I’m going to review that types file and confirm each of the object types and data needed. I just cut-n-pasted your code into other objects to validate that they would show up in the Home app.

Right now, locks, switches, fans, and lights work.

TODO:

- Fan rotation doesn’t show up.
- Light brightness needs to be throttled. It sends several on + brightness codes a second overwhelming my controller.
- Thermostat can’t be controlled
- Garagedoor control crashes:

[Garage Door] Set TargetPosition: 1
[Garage Door] Moving up
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:147
  this.getCharacteristic(name).setValue(value);
                              ^
TypeError: Cannot read property 'setValue' of undefined
    at Service.setCharacteristic (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:147:31)
    at HttpMulti.setTargetPosition (/vol/git/homebridge-httpmulti/index.js:271:10)
    at emit (events.js:118:17)
    at Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:155:10)
    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:681:22)
    at Array.forEach (native)
    at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:630:8)
    at HAPServer.emit (events.js:118:17)
    at HAPServer._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:770:10)
    at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:188:39)

- Get the status URL in place to provide a method to update object.
